danmarshall/deckgl-typings

- deck.gl__layers/index.d.ts
The polygon field should support both simple and complex polygons:
Example from the [API doc](http://deck.gl/#/documentation/deckgl-api-reference/layers/polygon-layer):
```
*     // Simple polygon (array of coords)
*     contour: [[-122.4, 37.7], [-122.4, 37.8], [-122.5, 37.8], [-122.5, 37.7], [-122.4, 37.7]],
*
*     // Complex polygon with holes (array of coords)
*     contour: [
*       [[-122.4, 37.7], [-122.4, 37.8], [-122.5, 37.8], [-122.5, 37.7], [-122.4, 37.7]],
*       [[-122.45, 37.73], [-122.47, 37.76], [-122.47, 37.71], [-122.45, 37.73]]
*     ],
```
> support simple and complex polygons (with holes)

- package.json
@danmarshall I just installed the latest typings and noticed that I'm getting the following error:
```
[error] TypeScript error node_modules/@types/deck.gl/index.d.ts:4:22 - error TS6053: File '<project-folder>/node_modules/@types/deck.gl__aggregation-layers/index.d.ts' not found.
4 /// <reference path="../deck.gl__aggregation-layers/index.d.ts" />
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@types/deck.gl/index.d.ts:73:9 - error TS7016: Could not find a declaration file for module '@deck.gl/aggregation-layers'. '<project-folder>/node_modules/@deck.gl/aggregation-layers/dist/es5/index.js' implicitly has an 'any' type.
Try `npm install @types/deck.gl__aggregation-layers` if it exists or add a new declaration (.d.ts) file containing `declare module '@deck.gl/aggregation-layers';` …
```
> Add folder deck.gl__aggregation-layers to indefinitely-typed postinstall

- deck.gl__aggregation-layers/index.d.ts
- deck.gl__core/index.d.ts
- deck.gl__geo-layers/index.d.ts
- deck.gl__layers/index.d.ts
- deck.gl__mesh-layers/index.d.ts
Hey @danmarshall I generated these from the documentation. I haven't committed the generation code as it only got me like 95% of the way and automating the last mile would be a lot of effort.
I think they're all legit and I'll test a couple of them in my project.
I left a lot of them as pretty naive typings but at least this gets the bulk of the effort done, people can tweak themselves to get better types. It at least stops things like the below:
```
const layer = new HeatmapLayer({
...
} as any);
```
> Add typings for layer props

- deck.gl__layers/index.d.ts
positionFormat (String, optional)
One of 'XYZ', 'XY'.
This prop is currently only effective in PathLayer, SolidPolygonLayer and PolygonLayer.
Default 'XYZ'.
https://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=positionformat-string-optional-
> add positionFormat prop for PathLayer, SolidPolygonLayer and PolygonLayer

- deck.gl__aggregation-layers/index.d.ts
The getColorValue functions argument type was wrongly a single value instead of an Array, I have changed it, so now it compiles with proper functionality.
Thanks for creating this type definition!
> changing getColorValue argument type from D to D[]

- deck.gl__react/index.d.ts
As seen in [the docs](https://deck.gl/#/documentation/submodule-api-reference/deckgl-react/deckgl). I used `any` for the type of the provider because correctly reflecting the provider type would require several more imports, and there's not much risk of screwing up and passing the wrong thing into this field.
> Add ContextProvider to props for React component

- deck.gl__layers/index.d.ts
**TL;DR** This PR allows 2D coordinates (i.e., without altitude) in a type `LayerPath`.
This TypeScript code 
```typescript
import { PathLayer } from '@deck.gl/layers';
interface Path {
path: [number, number][],
name: string,
color: [number, number, number]
}
// Taken from PathLayer API documentation:
// https://deck.gl/#/documentation/deckgl-api-reference/layers/path-layer
const DATA: Path[] = [{
path: [[-122.4, 37.7], [-122.5, 37.8], [-122.6, 37.85]],
name: 'Richmond - Millbrae',
color: [255, 0, 0]
}]
const pathlayer = new PathLayer({
data: DATA,
getPath: d => d.path,
})
```
yields the following error:
```typescript
example.ts:19:3 - error TS2322: Type '(d: Data) => [number, number][]' is not assignable to type '(d: Data) => LayerPath'.
Type '[number, number][]' is not assignable to …
```
> Allow 2-dimentional coordinates in a type LayerPath

- deck.gl__core/index.d.ts
While converting my React app to TypeScript, the compiler claimed `Object literal may only specify known properties, and 'opacity' does not exist in type 'TripsLayerProps<Trip>'`. So I added `opacity` definition to the underlying `LayerProps`.
Besides `opacity`, I also added some definitions for properties listed in [the documentation](https://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=properties). I didn't add definitions for unfamiliar properties, but I hope this PR brings a bit better coverage.
> Add missing definitions for LayerProps

- .gitignore
- deck.gl__layers/index.d.ts
Fixes #74 
- Fixed type of `getLineWidth` in `ScatterplotLayerProps`
- Added yarn.lock to gitignore
- Tests passed
> ScatterplotLayerProps getLineWidth type fixed (RGBAColor -> number)

- deck.gl/index.d.ts
- deck.gl__react/index.d.ts
> Expose _Cameralight, reinstate React DeckProps

- deck.gl__core/index.d.ts
- deck.gl__react/index.d.ts
* Adds DeckProps parameter to `React.Component`
* Adds optional string for DeckProps width and height https://github.com/visgl/deck.gl/blob/e948740f801cf91b541a9d7f3bba143ceac34ab2/modules/react/src/deckgl.js#L71-L72
Related to #85
> DeckProps to React.Component. Fixes DeckProps type

- deck.gl__react/index.d.ts
The documentation on the side is not clear on this point, but the examples are. Nothing uses width and height, for example. Layers can be added as children, so not required as props.
> Not all deck props are required in deckgl for react

- package.json
Some packages like `@luma.gl/constants` are missing from the `postinstall` hook and cannot be used.
This change adds every single module in the repo, which doesn't seem to break anything.
> Add missing subpackages to postinstall

- deck.gl__core/index.d.ts
Deck class has a canvas prop but it was missing. This PR adds support for it.
> Add canvas to DeckProps

- README.md
Fix description about how to install the project so the types are directly linked in the project, as a regular dependency.
Fixes #67
> Update README for install step

- deck.gl__core/index.d.ts
Viewport has a number of public (not prefixed with _) properties and it is convenient to be able to access them. Without this I get errors about accessing non-existing properties.
> Add public properties of Viewport.

- deck.gl__core/index.d.ts
- deck.gl__layers/index.d.ts
Updates the Polygon Layer prop types appropriately. You have to do a little bit of digging here, as there's an issue in the documentation regarding the `lineWidthScale` prop. The documentation states a boolean, but the example and code relies on a number:
https://github.com/visgl/deck.gl/blob/master/modules/layers/src/polygon-layer/polygon-layer.js#L39
> Update Polygon layer props

- deck.gl__core/index.d.ts
- deck.gl__layers/index.d.ts
As documented here -
https://deck.gl/docs/developer-guide/using-layers#accessors - accessor
functions receives 2 arguments, the object (D) and objectInfo.
ObjectInfo includes contextual information of the current element.
> add ObjectInfo parameter to attribute accessors

- deck.gl__core/index.d.ts
- deck.gl__react/index.d.ts
This adds a missing member to the DeckGL react component and two for the Deck object.
Together this makes it possible to use e.g. fitBounds from (math.gl)[https://math.gl/modules/web-mercator/docs/api-reference/web-mercator-utils] which requires the size of the Deck canvas as input.
> Fix missing deck member

- deck.gl__core/index.d.ts
The module is not part of deck.gl and should not be declared here.
Closes #145
> Remove declaration for "debug" module

- deck.gl__core/index.d.ts
This introduces a type describing the argument to `Layer.shouldUpdateState` and `Layer.udpateState`: `UpdateStateInfo<P>` where `P` is the type of the layer's props.
It also adds a `LayerChangeFlags` type attempting to describe the changeFlags, but deck.gl seems to be not very consistent in what types it uses for those ☹️ - perhaps it would be better to just have `any` for the members of `LayerChangeFlags`?
> Provide stricter typing for updateState and shouldUpdateState

- deck.gl__core/index.d.ts
- deck.gl__layers/index.d.ts
Some places explicitly don't use/allow alpha values
> Use RGBColor instead of RGBAColor where appropriate

- deck.gl__aggregation-layers/index.d.ts
- deck.gl__core/index.d.ts
- deck.gl__geo-layers/index.d.ts
- deck.gl__layers/index.d.ts
* Updated Layer.getPickingInfo to be more correct
* Removed getPickingInfo methods from Layer subclasses, since it's a core lifecycle method and there are no actual signature changes in subclasses
> More accurate getPickingInfo typings

- deck.gl__core/index.d.ts
An internal parameter, but necessary to use if implementing your own View
> Add type to ViewProps

- deck.gl__aggregation-layers/index.d.ts
- deck.gl__core/index.d.ts
- deck.gl__geo-layers/index.d.ts
- deck.gl__layers/index.d.ts
- deck.gl__mesh-layers/index.d.ts
- test/@deck.gl/ensure-consistent-layer-interfaces.ts
- Added a test (test/@deck.gl/ensure-consistent-layer-interfaces.ts) to ensure all Layer subclasses conform to the Layer interface
- Remove all  `updateState` and `shouldUpdateState` methods from Layer subclasses, since it's a standard Layer lifecycle method (and the different signatures were causing issues)
- A few other minor fixes to ensure consistent Layer interfaces
> Ensure consistent Layer interfaces, remove updateState from Layer subclasses

- deck.gl__core/index.d.ts
Small fix for solving issue https://github.com/danmarshall/deckgl-typings/issues/155, which is that `getTooltip?` in `DeckProps` had a missing return type according to the official documentation. More in-depth evidence in the linked issue.
------
Note: the linked issue was made by @argdiego, which is another account I have.
> Fixing getTooltip? return type declaration.

- deck.gl__geo-layers/index.d.ts
- deck.gl__layers/index.d.ts
Layer class accepts more than one property object in its constructor, so definitions are changed accordingly.
cf. https://deck.gl/docs/api-reference/core/layer#constructor-1
> Allow multiple properties in layer constructors

- deck.gl__aggregation-layers/index.d.ts
This is an undocumented prop that appears in the docs for some layers but not others.  It's definitely [in the original source code for Hexagon layer, though!](https://github.com/visgl/deck.gl/blob/master/modules/aggregation-layers/src/hexagon-layer/hexagon-layer.js#L41).  kepler.gl also lets folks change this behavior.
> hexagon: add colorScaleType prop

- deck.gl__aggregation-layers/index.d.ts
I think argument of getElevationValue in HexagonLayerProps should be array of D.
> fix array definition

- deck.gl__core/index.d.ts
I think ColorRange used to have a restriction capped at 6 colors, but it's more flexible now.
References:
* [deck.gl docs change](https://github.com/visgl/deck.gl/pull/5107/files)
* kepler.gl supports color palettes of multiple sizes
> ColorRange: don't restrict to 6 colors

- deck.gl__core/index.d.ts
- deck.gl__react/index.d.ts
This solves #179 by changing the type of `DeckProps.ContextProvider` and removing a now unnecessary type.
> Remove ContextProviderValue type to allow proper interop

- README.md
previously, I put the `deck.d.ts` in the root in a `types` folder and tried telling `tsconfig.json` to look there, etc but the info in https://github.com/danmarshall/deckgl-typings/issues/126 helped me figure it out and I thought it'd be helpful to include the details I was missing to the main README in case it helps others
> Update README.md with more specific install info

- deck.gl__core/index.d.ts
This solves #93, which prevents GeoJSON data from being accepted as the data parameter for the `GeoJsonLayer` type. This fix opens up the typing for all types.
> Simple addition to base layer data

- deck.gl__core/index.d.ts
Added properties:
```
parent?: HTMLElement;
pickable?: boolean;
```
Changed width and height to be optional:
```
width?: string | number;
height?: string | number;
```
> Missing props in DeckProps, optional width and height

- deck.gl__react/index.d.ts
Fixes #189, but I'm not sure if there isn't a better way to do this. My first attempt used this:
```typescript
export type DekcGLProps<T=ContextProviderValue> = DeckProps<T>;
export default class DeckGL<T=ContextProviderValue> extends React.Component<DeckGLProps<T>> {
constructor(props: Partial<DeckGLProps<T>>);
}
```
In other words put the `Partial` only on the constructor argument, but I was still getting the same error as in #189. Thoughts?
> Make all DeckGL props optional.

- deck.gl__core/index.d.ts
This documentation is incorrect: https://deck.gl/docs/api-reference/core/layer#parameters
The input is actually the argument to luma.gl `setParameters`.
I'll try to fix this independently in deck.gl, but I wanted to fix it here already.
Closes #87 
In the future, this will require further changes to reflect actually allowed luma.gl fields for this object.
> LayerProps: parameters is an object, not a function

- deck.gl__layers/index.d.ts
If constructor param of `PathLayer` is not specified, `new PathLayer()` will check type `LayerProps` instead of `PathLayerProps`.
> fix PathLayer constructor params

- deck.gl__core/index.d.ts
- deck.gl__geo-layers/index.d.ts
- deck.gl__layers/index.d.ts
Best reviewed commit by commit.
Most should be self explanatory, some might need more discussion:
- Draw options are passed into the model here: https://github.com/visgl/deck.gl/blob/017d960d95160c456204f781dceac41eafd49579/modules/core/src/lib/layer.js#L389, and I'm not sure where it's going; the existing structure does not match a luma.gl model either (https://luma.gl/modules/engine/docs/api-reference/model#drawoptions-object-boolean).
- `MVTLayerProps` is probably good to have when extending `MVTLayer`; but it isn't really necessary either.
- `userData` is found in deck.gl extensions like https://github.com/visgl/deck.gl/blob/1049956d723fe7a92c39ea203bc2b5c5fe00cc36/modules/mapbox/src/deck-utils.js#L124
> Various minor fixes and improvements

- deck.gl__layers/index.d.ts
Deck.gl polygon layer can handle  different types of polygons with `Position[]` only one type is covered. 
Corresponding Deck.gl documentation: 
[https://deck.gl/docs/api-reference/layers/solid-polygon-layer#getpolygon](https://deck.gl/docs/api-reference/layers/solid-polygon-layer#getpolygon)
[https://deck.gl/docs/api-reference/layers/polygon-layer#getpolygon](https://deck.gl/docs/api-reference/layers/polygon-layer#getpolygon)
In order to handle Polygons with polygonal holes in it. It can accept array of `Position[]` where 1st element is actual outer poygon and following polygons are holes in it. 
previously: `getPolygon?: (x: D) => Position[];`
now: `getPolygon?: (x: D) => Position[] | Position[][];`
Note: adding Flat simple polygon and object of shape {positions, holeIndices} in order …
> Added type for `getPolygon` data accessors.

- deck.gl/index.d.ts
After installing any package, We encounter this error: can not resolve @deck.gl/extensions.
> reference to deck.gl/extensions (#214)

- deck.gl__layers/index.d.ts
https://deck.gl/docs/upgrade-guide#deprecations
GeoJsonLayer's getRadius props is deprecated, replaced by getPointRadius.
> fix: getRadius -> getPointRadius

- deck.gl__extensions/index.d.ts
The purpose of this PR is to add FillStyleExtension (https://deck.gl/docs/api-reference/extensions/fill-style-extension) typing to @deck.gl/extensions. Thanks!
> fix: add FillStyleExtension to extensions

- deck.gl__core/index.d.ts
https://github.com/visgl/deck.gl/blob/master/modules/core/src/controllers/transition-manager.ts#L9-L15
I'm not sure if typing library is allowed to have literal. Here is my changes
```ts
export enum TRANSITION_EVENTS {
BREAK = 1,
SNAP_TO_END = 2,
IGNORE = 3
}
```
> TRANSITION_EVENTS as enum

- deck.gl__core/index.d.ts
- deck.gl__layers/index.d.ts
- deck.gl__react/index.d.ts
A collection of small touch-ups I've collected over time. Just running down a commit summary:
- <s>Removes math.gl and luma.gl types because they now have their own</s>
- Adds "_containerRef" to the DeckGL class
- LayerManager returns `Layer<any, any>` to better match all Layers.
- Uses math.gl's `Matrix4` for instances of `modelMatrix`
- Adds animationLoop, eventManager, layerManager, tooltip to Deck class
- Adds "el" to the Tooltip class
- Extracts an "InteractionState" type and uses it accordingly
- Re-adds the "id" parameter to Scatterplot.getShaders
> Misc updates

- deck.gl/index.d.ts
- deck.gl__core/index.d.ts
- deck.gl__layers/index.d.ts
A new `common` unit type has been added which is now available in addition to the previously available types `meters` and `pixels`.
See [supported units docs](https://deck.gl/docs/developer-guide/coordinate-systems#supported-units) and also [scatterplot docs](https://deck.gl/docs/api-reference/layers/scatterplot-layer#radiusunits).
> WidthUnits/radiusUnits: add new 'common' unit type

- deck.gl__core/index.d.ts
- deck.gl__geo-layers/index.d.ts
- deck.gl__layers/index.d.ts
- Adapt props from sub-layers to GeoJson layer
- Layer clone accepts partial props
- Deck layers prop accepts falsy item
- TileLayer `getTileData` returns `Promise` with falsy value
- Add missing props to ScatterplotLayerProps. related to #227
- Add missing props to TextLayerProps
> GeoJson layer props

- deck.gl__layers/index.d.ts
Remove param and corresponding doc to make normalize function correct.
Add number type for number input.
Based on issue: https://github.com/visgl/deck.gl/issues/6839
> Remove unused param and doc from solid-polygon-layer's normalize function

- .gitignore
- deck.gl__layers/index.d.ts
Fixed path props type correctness in constructor. As far as I understand, all props are passed to the constructor, not a subset, so generic `P` from `P extends PathLayerProps<D>` should be passed instead of `PathLayerProps<D>`.
`P` basically differs from normal props when an extensions is used, for example the `PathStyleExtension`, that adds more properties as valid on PathLayerProps.
_*Note that I have also added on .gitignore the /.idea fodler that are the editor settings from Jetbrains editors._
> Fixed path props type in constructor.

- deck.gl__geo-layers/index.d.ts
Adding the property [`fadeTrail`](https://deck.gl/docs/api-reference/geo-layers/trips-layer#fadetrail) that was missing in the TripsLayer.
> fix/missing fadeTrail property in TripsLayer

- deck.gl__core/index.d.ts
Add `drawPickingColors` to DeckProps
ref:
https://github.com/visgl/deck.gl/blob/8.8-release/modules/core/src/lib/deck.ts#L225
> Add drawPickingColors to DeckProps
