danmarshall/deckgl-typings

deck.gl/index.d.ts
=> removed /index from the name

@deck.gl/core/index.d.ts
There may be a better place to put this, I'm not sure if it's associated with the AttributeManager ...
=> added TransitionTiming

deck.gl__layers/index.d.ts, luma.gl/index.d.ts, package.json, test/index.d.ts, test/tsconfig.json
=> Texturefix

package.json
=> remove unused deps

deck.gl__mapbox/index.d.ts
=> Add MapboxLayerProps

deck.gl__extensions/index.d.ts
https://github.com/visgl/deck.gl/blob/master/modules/extensions/src/path-style/path-style.js
=> added PathStyleExtension types for deck.gl/extensions

deck.gl__geo-layers/index.d.ts
=> getTimestamps has a second param

deck.gl__layers/index.d.ts
The other items in the issue are already fixed
=> Update PointCloudLayerProps to Allow for Elevation closes #75

deck.gl__geo-layers/index.d.ts
This just adds S2LayerProps and getS2Token for it.
=> S2Layer Missing Properties #86

deck.gl__aggregation-layers/index.d.ts, deck.gl__core/index.d.ts, deck.gl__geo-layers/index.d.ts, deck.gl__layers/index.d.ts, deck.gl__mesh-layers/index.d.ts
using any at the moment, will update whenever i figure out what it is. For now, this will help in creating sub-classes.
=> initializeState takes a context as an arg

deck.gl__core/index.d.ts
=> Default props

deck.gl__aggregation-layers/index.d.ts, deck.gl__core/index.d.ts, deck.gl__geo-layers/index.d.ts, deck.gl__layers/index.d.ts, deck.gl__mesh-layers/index.d.ts
=> Proper props

deck.gl__geo-layers/index.d.ts
The deck.gl docs were incorrect https://github.com/visgl/deck.gl/pull/4869
=> TerrainLayer [rgb]Scale -> [rgb]Scaler

deck.gl__core/index.d.ts
Fix issue where constructor and defined props differ
=> Fix constructor to follow extends props type

deck.gl__core/index.d.ts
Added an interface with options to the DeckController following docs from https://github.com/visgl/deck.gl/blob/master/docs/api-reference/core/controller.md
=> Added ControllerOptions

deck.gl__core/index.d.ts
After seeing the issue #121 I simply set this prop to DeckGL component.
=> Added ContextProvider to DeckGL props fixes #121

package.json
=> Remove deleted folders from post-install script

deck.gl__core/index.d.ts
https://deck.gl/docs/api-reference/core/controller#options
=> Updated controller options types

deck.gl__core/index.d.ts
https://deck.gl/docs/api-reference/core/deck#_typedarraymanagerprops
=> Update interface DeckProps

deck.gl__aggregation-layers/index.d.ts, deck.gl__core/index.d.ts, package.json
https://deck.gl/docs/api-reference/aggregation-layers/heatmap-layer#aggregation
https://deck.gl/docs/api-reference/core/deck#metrics
=> Update HeatmapLayerProps & Metrics

deck.gl__core/index.d.ts
https://deck.gl/docs/api-reference/react/deckgl#contextprovider
=> ContextProviderValue

deck.gl__core/index.d.ts
See https://deck.gl/docs/developer-guide/coordinate-systems#supported-coordinate-systems
=> Layer coordinateOrigin has optional Z coordinate

deck.gl__core/index.d.ts
See https://deck.gl/docs/api-reference/core/layer#draw  and https://github.com/visgl/deck.gl/blob/2b921cb4281a5857a49b064f88c8f1de0c23c0aa/modules/core/src/lib/layer.js#L752
=> Layer draw method

deck.gl__core/index.d.ts
See https://deck.gl/docs/api-reference/core/view#constructor-1  and https://github.com/visgl/deck.gl/blob/c60064d4e60bda83ee3dc276e421d4e1faa08896/modules/core/src/views/view.js#L7
=> View Props

deck.gl__core/index.d.ts, deck.gl__geo-layers/index.d.ts, deck.gl__layers/index.d.ts, deck.gl__mesh-layers/index.d.ts
See https://deck.gl/docs/api-reference/geo-layers/terrain-layer#properties
=> Types for number arrays

deck.gl__mesh-layers/index.d.ts
See https://github.com/visgl/deck.gl/blob/38945f171db1b14e5c2442d57d96060ee01f2fd7/modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js#L78
=> Add _instanced to SimpleMeshLayerProps

deck.gl__layers/index.d.ts
See https://deck.gl/docs/api-reference/layers/bitmap-layer#properties
=> Fix BitmapLayerProps

deck.gl__arcgis/index.d.ts, deck.gl__carto/index.d.ts, package-lock.json, package.json, scripts/convert.js, test/@deck.gl/arcgis.d.ts, test/@deck.gl/carto.d.ts
=> add arcgis & carto

deck.gl__core/index.d.ts
Via the [deck.gl docs](https://deck.gl/docs/api-reference/core/layer#loaders)
=> Add loaders to LayerProps

package.json
=> install arcgis & carto

deck.gl__core/index.d.ts, test/@deck.gl/ensure-consistent-layer-interfaces.ts
See https://github.com/visgl/deck.gl/blob/7decad2a29c156a34d7e816a45beffde55ebd49b/modules/core/src/lifecycle/component.js#L12
=> The default Layer constructor is variadic

deck.gl__layers/index.d.ts
Added constructor for PathLayer
=> Fixes #193

deck.gl__layers/index.d.ts
They require at least one object.
#194 broke this
=> The core Layer constructors are variadic

deck.gl__core/index.d.ts
API docs: https://deck.gl/docs/api-reference/core/layer#loadoptions
=> LayerProps: add loadOptions

deck.gl__core/index.d.ts
Companion for https://github.com/visgl/deck.gl/pull/5870
=> Deck: canvas is optional and can also be string

.gitignore, deck.gl__geo-layers/index.d.ts, deck.gl__layers/index.d.ts
- TileLayer: getTileData signal
- MVTLayer: uniqueIdProperty
=> Add props to TileLayer and MVTLayer

deck.gl__mesh-layers/index.d.ts
https://deck.gl/docs/developer-guide/using-layers#accessors
=> Added accessor context info

deck.gl__layers/index.d.ts
https://deck.gl/docs/api-reference/layers/text-layer#background
=> Added background flag for TextLayerProps

deck.gl__mesh-layers/index.d.ts
https://github.com/visgl/deck.gl/blob/614d871484efec9b3353c89b622dfc51c2b25520/modules/mesh-layers/src/utils/matrix.ts#L80
⎡ 1  0  0  0⎤
⎢ 0  1  0  0⎥
⎢ 0  0  1  0⎥
⎣ 0  0  0  1⎦
=> Fixet type matrix

deck.gl__arcgis/index.d.ts
Issue is addressed under this PR.
https://github.com/visgl/deck.gl/issues/6033
=> Updates to also allow the ESRI layer from arcgiscore directly

deck.gl__react/index.d.ts
Fix breaking change introduced in React 18 referenced in #242
=> Update types for React 18

deck.gl/index.d.ts, test/deck.gl.ts
Hi, @danmarshall 
I send you PR to fix this issue. 
#247
=> fix to reference google-maps
